# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'FandomLive' do
use_frameworks!
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'Google/SignIn'
pod 'Alamofire'
pod 'Kingfisher'
pod 'Connectivity'
pod "Codextended"
pod 'SVProgressHUD'
pod 'Repeat'
pod 'IQKeyboardManagerSwift'
pod 'SDWebImage'
pod 'FCUUID'
pod 'iOSDropDown'
pod ’SJSegmentedScrollView’, ‘1.3.8'
pod 'Loaf'
end 
